# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Set timeout for commands
command_timeout = 2000

# add custom format
format = """
[î‚¶](cyan)\
$directory\
[î‚°](fg:cyan bg:red)\
$git_branch\
$git_commit\
[î‚°](fg:red bg:147)\
$php\
[î‚°](fg:147 bg:yellow)\
$memory_usage\
[î‚°](fg:yellow bg:green)\
$time\
[î‚°](fg:green)\
$line_break\
$container\
$character
"""

[character] # The name of the module we are configuring is "character"
success_symbol = "[ âžœ](bold green)"
error_symbol = "[ âžœ](bold red)"

[directory]
format = "[ $path ]($style)[$read_only]($read_only_style)"
style = "bg:cyan black"

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "bg:red black"

[git_commit]
format = '[ \($hash$tag\) ]($style)'
style = "bg:red black"

[docker_context]
format = "via [ðŸ‹ $context](blue bold) "

[memory_usage]
disabled = false
format = "[ ó°› $ram ]($style)"
threshold = -1
style = "bg:yellow black"

[status]
disabled = false
format = '[\[$symbol $common_meaning\]]($style) '
map_symbol = true
pipestatus = true
pipestatus_format = '\\[$pipestatus\\] => [\[$symbol $common_meaning\]]($style)'

[php]
format = "[ î˜ˆ $version ](bg:147 black)"

[time]
disabled = false
time_format = "%R"
style = "bg:green black"
format = "[ ó±‘’ $time ]($style)"
